language: node_js
sudo: false
node_js: 4.1
before_script:
- node --version
- npm --version
- npm install -g grunt-cli
script:
- grunt test-travis --verbose
- grunt coveralls:travis
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then grunt saucelabs-test; fi
before_deploy:
- npm install
- grunt build
- grunt dist
deploy:
  provider: npm
  email: susukang98@gmail.com
  api_key:
    secure: TYJfuTLZKbYvTskuMlmuKnQb5F35GFPN2AqSf0RtZYWGLozIaIkKcpTVbjzo859FWuxPjci53FGiJih3+0iVfIC39CDTrFZutubn8qduOfRAVTL1WzeQvdww8miJNwUY59HmoOa78OtbNCVg/N7zFSZzRXAcgje8IADQFIISwk8=
  on:
    tags: true
    branch: develop
addons:
  sauce_connect: true
env:
  global:
    - SAUCE_USERNAME: summernoteis
    - SAUCE_ACCESS_KEY: b4657a9b-6a55-4f89-92ef-c507e89b69fb
