language: node_js
sudo: false
node_js: 4.1
before_script:
- node --version
- npm --version
- npm install -g grunt-cli
script:
- grunt test-travis --verbose
- grunt coveralls:travis
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then grunt saucelabs-test; fi
before_deploy:
- npm install
- grunt build
- grunt dist
deploy:
  provider: npm
  email: susukang98@gmail.com
  api_key:
    secure: TYJfuTLZKbYvTskuMlmuKnQb5F35GFPN2AqSf0RtZYWGLozIaIkKcpTVbjzo859FWuxPjci53FGiJih3+0iVfIC39CDTrFZutubn8qduOfRAVTL1WzeQvdww8miJNwUY59HmoOa78OtbNCVg/N7zFSZzRXAcgje8IADQFIISwk8=
  on:
    tags: true
    branch: develop
env:
  global:
    - SAUCE_USERNAME: summernoteis
    - SAUCE_ACCESS_KEY: UthjfVQ67TlebNYGcxFmjypivlxiblqTJ+GY2keHOzmHtx91aaP3k8LfylDuwGbGV9REApCJvHeS0pOLy9ZFDMzoKhiXoO7NwrJZIjNmzOVxDbdDMxxX2oBsCN78DRsQsuQLt720Hv94qP7SRQ4x1/IC8MIk5ybchuOvFOMA694=
